"""Repository discovery and manifest parsing across ecosystems."""

from __future__ import annotations

from pathlib import Path

from repoviz.manifests import command_entry_target, parse_project_file
from repoviz.repo import Repository

POLYGLOT = {
    # npm workspace monorepo
    "package.json": '{"name": "mono", "private": true, "workspaces": ["packages/*"], '
                    '"devDependencies": {"dependency-cruiser": "^16"}}',
    "packages/ui/package.json": '{"name": "@acme/ui", "version": "1.0.0", "main": "dist/index.js", '
                                '"dependencies": {"react": "^18"}}',
    "packages/ui/src/index.ts": "export function Button() { return 1 }\n",
    "packages/app/package.json": '{"name": "@acme/app", "private": true, "dependencies": {"@acme/ui": "workspace:*"}, '
                                 '"scripts": {"start": "node src/server.js"}}',
    "packages/app/src/server.js": "const { Button } = require('@acme/ui');\nButton();\n",
    "tsconfig.json": '{ // comment\n "compilerOptions": {"baseUrl": ".", "paths": {"@ui/*": ["packages/ui/src/*"]},},\n}',
    # Rust workspace
    "crates/Cargo.toml": '[workspace]\nmembers = ["core", "cli"]\n',
    "crates/core/Cargo.toml": '[package]\nname = "core"\nversion = "0.1.0"\n[dependencies]\nserde = "1"\n',
    "crates/core/src/lib.rs": "pub fn f() {}\n",
    "crates/cli/Cargo.toml": '[package]\nname = "cli"\nversion = "0.1.0"\n[dependencies]\ncore = { path = "../core" }\n',
    "crates/cli/src/main.rs": "fn main() {}\n",
    # Go
    "svc/go.mod": "module example.com/svc\n\ngo 1.22\n\nrequire (\n\tgithub.com/pkg/errors v0.9.1 // indirect\n)\n",
    "svc/main.go": 'package main\n\nimport (\n\t"fmt"\n\t"example.com/svc/internal/db"\n)\n\nfunc main() { fmt.Println(db.X) }\n',
    "svc/internal/db/db.go": "package db\n\nvar X = 1\n",
    # Maven multi-module
    "java/pom.xml": '<project xmlns="http://maven.apache.org/POM/4.0.0"><groupId>org.acme</groupId><artifactId>parent</artifactId>'
                    '<version>1</version><packaging>pom</packaging><modules><module>api</module><module>web</module></modules></project>',
    "java/api/pom.xml": '<project><parent><groupId>org.acme</groupId></parent><artifactId>api</artifactId></project>',
    "java/web/pom.xml": '<project><parent><groupId>org.acme</groupId></parent><artifactId>web</artifactId><packaging>war</packaging>'
                        '<dependencies><dependency><groupId>org.acme</groupId><artifactId>api</artifactId></dependency>'
                        '<dependency><groupId>junit</groupId><artifactId>junit</artifactId><scope>test</scope></dependency>'
                        '</dependencies></project>',
    "java/web/src/main/java/App.java": "class App {}\n",
    # .NET
    "dotnet/All.sln": 'Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Api", "Api\\Api.csproj", "{1}"\nEndProject\n',
    "dotnet/Api/Api.csproj": '<Project Sdk="Microsoft.NET.Sdk.Web"><ItemGroup><PackageReference Include="Serilog" Version="3.0.0" />'
                             '</ItemGroup></Project>',
    "dotnet/Api/Program.cs": "class Program {}\n",
    # Containers, deployment, CI, docs, architecture tooling
    "Dockerfile": "FROM node:20 AS build\nCOPY packages /app/packages\nFROM build\nCMD [\"node\", \"packages/app/src/server.js\"]\n",
    "docker-compose.yml": "services:\n  app:\n    build: .\n    depends_on: [db]\n  db:\n    image: postgres:16\n",
    ".github/workflows/ci.yml": "name: CI\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n  deploy:\n    needs: test\n    runs-on: ubuntu-latest\n",
    "deploy/k8s/app.yaml": "apiVersion: apps/v1\nkind: Deployment\n",
    "docs/index.md": "# Docs\n", "docs/guide.md": "x\n", "docs/api.md": "x\n", "docs/faq.md": "x\n",
    ".importlinter": "[importlinter]\nroot_package = x\n",
    "docs/adr/0001-record.md": "# ADR\n",
    # Generated and vendored code; an unsupported language
    "dist/bundle.js": "var x = 1;\n",
    "gen_pb2.py": "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n",
    "vendor/lib/thing.py": "x = 1\n",
    "scripts/tool.hs": "main = putStrLn \"hi\"\n",
    "tools/check.py": "import json\n",
}


def test_polyglot_discovery(make_repo) -> None:
    repo = make_repo(POLYGLOT)
    prof = Repository(repo.path).discover()
    langs = {l["language"]: l for l in prof.languages}
    assert langs["python"]["supported"] and langs["typescript"]["supported"] and langs["go"]["supported"]
    assert not langs["haskell"]["supported"] and not langs["rust"]["supported"]
    codes = {d.code for d in prof.diagnostics}
    assert "unsupported-language" in codes
    projects = {p["path"]: p for p in prof.projects}
    assert projects["packages/app"]["workspace"] == "package.json"
    assert projects["crates/cli"]["workspace"] == "crates/Cargo.toml"
    assert projects["java/web"]["role"] == "application" and projects["java/api"]["role"] == "library"
    assert projects["dotnet/Api"]["role"] == "application"
    ws = {w["path"]: w["members"] for w in prof.workspaces}
    assert ws["package.json"] == ["packages/app", "packages/ui"]
    assert ws["crates/Cargo.toml"] == ["crates/cli", "crates/core"]
    assert ws["java/pom.xml"] == ["java/api", "java/web"]
    assert {c["kind"] for c in prof.containers} == {"dockerfile", "compose"}
    assert prof.ci[0]["provider"] == "github-actions" and prof.ci[0]["jobs"] == ["deploy", "test"]
    assert any(d["kind"] == "kubernetes" for d in prof.deployment)
    assert any(d["path"] == "docs" for d in prof.docs)
    tools = {t["tool"] for t in prof.architecture_config}
    assert {"import-linter", "architecture-decision-records"} <= tools
    assert {t["tool"] for t in prof.dependency_tools} >= {"import-linter", "dependency-cruiser"}
    assert any(g["path"] == "dist" for g in prof.generated)
    assert "gen_pb2.py" in prof.generated_paths
    assert any(v["path"] == "vendor" for v in prof.vendored)
    assert "dist/bundle.js" not in prof.included_files and "vendor/lib/thing.py" not in prof.included_files
    kinds = {e["kind"] for e in prof.entry_points}
    assert {"cargo-bin", "go-main", "container-cmd", "script"} <= kinds
    assert prof.default_branch == "main" and prof.branch == "main"


def test_polyglot_snapshot_dependencies(make_repo) -> None:
    repo = make_repo(POLYGLOT)
    snap = Repository(repo.path).snapshot("HEAD")
    idx = snap.node_index()
    deps = {(idx[e.source_id].qualified_name, idx[e.target_id].qualified_name, e.relationship)
            for e in snap.dependency_edges if e.direct}
    assert ("@acme/app", "@acme/ui", "depends-on") in deps  # npm workspace protocol
    assert ("cli", "core", "depends-on") in deps  # cargo path dependency
    assert ("org.acme:web", "org.acme:api", "depends-on") in deps  # maven module dependency
    assert ("packages/app/src/server", "packages/ui/src/index", "imports") in deps  # workspace import -> source
    assert ("example.com/svc/main.go", "example.com/svc/internal/db", "imports") in deps  # go internal import
    services = {n.name for n in snap.components if n.component_type == "service"}
    assert services == {"app", "db"}
    assert any(idx[e.source_id].name == "app" and idx[e.target_id].name == "db" for e in snap.dependency_edges)
    # Unsupported languages are structural nodes, not failures.
    hs = snap.find(path="scripts/tool.hs")
    assert hs is not None and "unsupported" in hs.tags
    assert not [d for d in snap.diagnostics if d.severity == "error"]


def test_config_overrides_discovery(make_repo) -> None:
    repo = make_repo({
        "code/pkg/mod.py": "import pkg.other\n", "code/pkg/other.py": "", "checks/test_x.py": "",
        ".repoviz.toml": 'source_roots = ["code"]\ntest_roots = ["checks"]\ndocs_roots = ["notes"]\n'
                         'exclude = ["legacy/**"]\n[components.core]\npaths = ["code/**"]\n',
        "legacy/old.py": "x = 1\n", "notes/readme.txt": "x",
    })
    r = Repository(repo.path)
    prof = r.discover()
    assert [s["path"] for s in prof.source_roots] == ["code"]
    assert prof.test_roots[0]["path"] == "checks" and "checks/test_x.py" in prof.test_paths
    assert "legacy/old.py" not in prof.included_files
    snap = r.snapshot()
    mod = snap.find(path="code/pkg/mod.py")
    assert mod.qualified_name == "pkg.mod"  # namespace package under the configured root
    comp = snap.node(mod.metadata["component_id"])
    assert comp.name == "core" and "configured" in comp.tags


def test_plain_directory_without_git(make_repo) -> None:
    repo = make_repo({"app/main.py": "import app.util\n", "app/__init__.py": "", "app/util.py": ""}, git=False)
    r = Repository(repo.path)
    assert not r.is_git
    snap = r.snapshot()
    assert snap.kind == "filesystem"
    assert any(d.code == "git-unavailable" for d in snap.diagnostics)
    assert any(e.relationship == "imports" for e in snap.dependency_edges)


# --------------------------------------------------------------------------- manifest parsers


def parse(path: str, text: str, files: set[str] | None = None):
    files = files or set()
    return parse_project_file(path, text, lambda p: p in files or (p.endswith("/") and any(f.startswith(p) for f in files)))


def test_pyproject_variants() -> None:
    md = parse("pkg/pyproject.toml", """
[project]
name = "demo"
dependencies = ["requests>=2 ; python_version>'3'", "local @ file:../lib"]
[project.optional-dependencies]
dev = ["pytest"]
[project.scripts]
demo = "demo.cli:main"
[dependency-groups]
lint = ["ruff"]
[tool.poetry.dependencies]
python = "^3.11"
flask = {version = "^3", optional = true}
[tool.uv.workspace]
members = ["libs/*"]
[tool.hatch.build.targets.wheel]
packages = ["src/demo"]
[tool.importlinter]
root_package = "demo"
""")
    deps = {d.name: d for d in md.dependencies}
    assert deps["requests"].spec == ">=2" and deps["requests"].scope == "runtime"
    assert deps["local"].local_path == "lib"
    assert deps["pytest"].scope == "optional:dev" and deps["ruff"].scope == "group:lint"
    assert deps["flask"].scope == "optional" and "python" not in deps
    assert md.entry_points[0].target == "demo.cli:main" and md.role == "application"
    assert md.workspace_members == ["pkg/libs/*"]
    assert "pkg/src" in md.source_roots
    assert "importlinter" in md.metadata["tool_config"]
    assert parse("pyproject.toml", "not = [valid").errors


def test_setup_py_is_never_executed(tmp_path: Path) -> None:
    marker = tmp_path / "EXECUTED"
    text = f"""
import os
open({str(marker)!r}, "w").write("pwned")
REQS = ["click>=8"]
from setuptools import setup
setup(name="legacy", version="0.1", install_requires=REQS,
      entry_points={{"console_scripts": ["legacy = legacy.main:run"]}}, package_dir={{"": "src"}},
      extras_require={{"x": ["rich"]}}, tests_require=compute())
"""
    md = parse("setup.py", text)
    assert not marker.exists()
    assert md.name == "legacy" and {d.name for d in md.dependencies} == {"click", "rich"}
    assert md.entry_points[0].target == "legacy.main:run" and md.source_roots == ["src"]
    assert md.metadata["dynamic_keywords"] == ["tests_require"]


def test_other_python_manifests() -> None:
    cfg = parse("setup.cfg", "[metadata]\nname = x\n[options]\ninstall_requires =\n  attrs\n  six>=1\n"
                            "package_dir =\n  =src\n[options.entry_points]\nconsole_scripts =\n  x = x.cli:main\n")
    assert [d.name for d in cfg.dependencies] == ["attrs", "six"] and cfg.source_roots == ["src"]
    req = parse("requirements-dev.txt", "# c\n-r base.txt\n-e ./libs/core\nDjango==5.0 ; python_version > '3'\n--index-url x\n")
    assert [d.name for d in req.dependencies] == ["core", "Django"]
    assert req.dependencies[0].local_path == "libs/core" and req.dependencies[1].scope == "dev"
    assert req.metadata["includes"] == ["base.txt"]


def test_js_rust_go_jvm_dotnet_manifests() -> None:
    pkg = parse("web/package.json", '{"name": "w", "bin": {"w": "bin/w.js"}, "dependencies": {"a": "file:../a", "b": "workspace:^"}}')
    assert pkg.role == "application" and pkg.entry_points[0].target == "web/bin/w.js"
    assert pkg.dependencies[0].local_path == "a" and pkg.dependencies[1].workspace
    cargo = parse("Cargo.toml", '[package]\nname = "x"\n[dependencies]\ny = { workspace = true }\n'
                                "[target.'cfg(unix)'.dependencies]\nlibc = \"0.2\"\n[[bin]]\nname = \"tool\"\n")
    assert {d.name for d in cargo.dependencies} == {"y", "libc"} and cargo.entry_points[0].name == "tool"
    gomod = parse("svc/go.mod", "module m\n\nrequire (\n\tx.io/y v1.0.0\n\tz.io/w v2.0.0 // indirect\n)\nreplace x.io/y => ../y\n")
    assert gomod.name == "m" and gomod.dependencies[0].local_path == "y"
    assert gomod.dependencies[1].scope == "indirect"
    gradle = parse("app/build.gradle.kts", 'plugins { application }\ndependencies {\n  implementation(project(":core"))\n'
                                           '  testImplementation("junit:junit:4.13")\n}\napplication { mainClass.set("A") }\n')
    assert gradle.role == "application"
    assert {(d.name, d.scope, d.workspace) for d in gradle.dependencies} == {(":core", "runtime", True), ("junit:junit", "test", False)}
    settings = parse("settings.gradle", "rootProject.name = 'r'\ninclude ':app', ':libs:core'\n")
    assert settings.workspace_members == ["app", "libs/core"]
    csproj = parse("A/A.csproj", '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>'
                                 '<ItemGroup><ProjectReference Include="..\\B\\B.csproj" /></ItemGroup></Project>')
    assert csproj.role == "application" and csproj.dependencies[0].local_path == "B"


def test_containers_and_commands() -> None:
    df = parse("svc/Dockerfile", "FROM python:3.12 AS base\nRUN pip install \\\n  x\nCOPY . /app\n"
                                 "ENTRYPOINT [\"gunicorn\", \"-b\", \"0.0.0.0\", \"app.wsgi:application\"]\nEXPOSE 8000\n")
    assert df.dependencies[0].name == "python:3.12" and df.metadata["expose"] == ["8000"]
    assert df.entry_points[0].target == "app.wsgi:application" and df.entry_points[0].target_kind == "python-callable"
    assert command_entry_target("python -m pkg.cli --x") == ("pkg.cli", "python-module")
    assert command_entry_target("node ./dist/server.js") == ("dist/server.js", "file")
    assert command_entry_target("make deploy") is None
    compose = parse("compose.yaml", "services:\n  api:\n    build:\n      context: ./api\n    depends_on:\n      db:\n        condition: x\n  db:\n    image: pg\n")
    svcs = compose.metadata["services"]
    assert svcs["api"]["build_context"] == "api" and svcs["api"]["depends_on"] == ["db"]
    broken = parse("package.json", "{nope")
    assert broken.errors and broken.kind == "package.json"


# --------------------------------------------------------------------------- compose system (#22)

SYSTEM = {
    "app/__init__.py": "",
    "app/main.py": "app = object()\n",
    "app/worker.py": "celery = object()\n",
    "frontend/package.json": '{"name": "frontend", "scripts": {"start": "node server.js"}}',
    "frontend/server.js": "console.log(1)\n",
    "frontend/Dockerfile": "FROM node:20\nCOPY . /app\nCMD [\"node\", \"server.js\"]\n",
    "Dockerfile": "FROM python:3.12\nCOPY . /app\n",
    "docker-compose.yml": """
services:
  api:
    build: .
    image: acme/api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports: ["8000:8000"]
    environment:
      MONGODB_URL: mongodb://admin:hunter2secret@mongo:27017/app
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: s3cr3t-value-never-shown
    depends_on: [mongo, redis]
    volumes: [uploads:/data/uploads]
  worker:
    build: .
    command: celery -A app.worker worker -l info
    environment:
      - CELERY_BROKER_URL=redis://redis:${REDIS_PORT:-6379}/0
      - API_URL=http://api:8000
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - uploads:/data/uploads
      - ./local:/local
  frontend:
    build: ./frontend
    environment:
      BACKEND_URL: http://api:8000
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
  mongo:
    image: mongo:7
    volumes: [mongo_data:/data/db]
volumes:
  uploads:
  mongo_data:
""",
    "docker-compose.prod.yml": """
services:
  api:
    image: acme/api:1.4
    command: gunicorn -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker app.main:app
    ports: ["80:8000"]
  worker:
    image: acme/api:1.4
    command: celery -A app.worker worker -l warning
  frontend:
    image: acme/frontend:1.4
  redis:
    image: redis:7
  mongo:
    image: mongo:7
""",
}


def test_compose_system_services(make_repo) -> None:
    import json

    repo = make_repo(SYSTEM)
    r = Repository(repo.path)
    snap = r.snapshot("WORKTREE")
    idx = snap.node_index()
    services = {n.name: n for n in snap.components if n.component_type == "service"}
    assert sorted(services) == ["api", "frontend", "mongo", "redis", "worker"]  # one per name, not one per file
    assert all(n.metadata["variants"] == ["base", "prod"] for n in services.values())
    kinds = {name: n.metadata["service_kind"] for name, n in services.items()}
    assert kinds == {"api": "first-party", "worker": "first-party", "frontend": "first-party", "redis": "cache",
                     "mongo": "database"}
    assert "infrastructure" in services["redis"].tags and "first-party" in services["api"].tags
    assert services["api"].metadata["differences"]["ports"] == {"base": ["8000:8000"], "prod": ["80:8000"]}
    edges = {(idx[e.source_id].name, idx[e.target_id].qualified_name, e.relationship): e for e in snap.dependency_edges}
    assert ("api", "app.main", "runs") in edges and ("worker", "app.worker", "runs") in edges
    assert ("frontend", "frontend/server", "runs") in edges  # from its Dockerfile's CMD, in its build context
    assert ("api", "mongo", "starts-after") in edges and ("worker", "redis", "starts-after") in edges
    talks = {(s, t): e.metadata["label"] for (s, t, rel), e in edges.items() if rel == "talks-to"}
    assert talks[("api", "mongo")] == "mongodb:27017" and talks[("api", "redis")] == "port 6379"
    assert talks[("worker", "redis")] == "redis:6379" and talks[("frontend", "api")] == "http:8000"
    assert edges[("api", "worker", "shares-volume")].metadata["label"] == "uploads"
    root = next(n for n in snap.components if n.component_type == "repository")
    assert sorted(t for (s, t, rel) in edges if s == "api" and rel == "builds") == sorted(["Dockerfile", root.qualified_name])
    assert ("redis", "redis:7-alpine", "depends-on") in edges  # infrastructure: its image
    # entry points: one per first-party service, with its variants; no infrastructure command
    prof = r.discover()
    compose_eps = [e for e in prof.entry_points if e["kind"] == "compose-command"]
    assert sorted(e["name"] for e in compose_eps) == ["api (compose)", "worker (compose)"]
    assert all(e["variants"] == ["base", "prod"] for e in compose_eps)
    assert not any("redis-server" in json.dumps(e) for e in prof.entry_points)
    # environment values never reach the snapshot, only variable names
    dumped = json.dumps(snap.to_dict())
    assert "hunter2secret" not in dumped and "s3cr3t-value-never-shown" not in dumped and "JWT_SECRET" in dumped
